application:    flowing-bonito-795
version:        1
runtime:        php
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /adminer
          static_dir: public/adminer

        - url: /aws
          static_dir: public/aws

        - url: /css
          static_dir: public/css

        - url: /fonts
          static_dir: public/fonts

        - url: /images
          static_dir: public/images

        - url: /js
          static_dir: public/js

        - url: /loading
          static_dir: public/loading

        - url: /packages
          static_dir: public/packages

        - url: /photos
          static_dir: public/photos

        - url: /weather-icons
          static_dir: public/weather-icons

        - url: /xslt
          static_dir: public/xslt

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env\.php).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$